"""Añadir tabla de usuarios

Revision ID: 2b70fe93eefd
Revises: a48997c6313b
Create Date: 2025-10-17 15:13:26.900519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b70fe93eefd'
down_revision = 'a48997c6313b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
